/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./popup/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#794225",
        "surface-container-highest": "#e0e2e6",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#424750",
        "inverse-on-surface": "#eff1f5",
        "tertiary-fixed-dim": "#99d595",
        "surface-container-low": "#f2f4f8",
        "background": "#f7f9fd",
        "tertiary-container": "#86c182",
        "surface": "#f7f9fd",
        "secondary": "#895032",
        "on-secondary-fixed": "#341100",
        "inverse-primary": "#a8c8ff",
        "outline-variant": "#c3c6d2",
        "on-primary-container": "#094583",
        "secondary-container": "#feb28d",
        "on-secondary-fixed-variant": "#6d391d",
        "tertiary": "#336a35",
        "primary-fixed-dim": "#a8c8ff",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ec",
        "surface-bright": "#f7f9fd",
        "primary-fixed": "#d5e3ff",
        "secondary-fixed-dim": "#ffb692",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#19511f",
        "on-tertiary-fixed": "#002205",
        "on-surface": "#191c1f",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#0e4685",
        "primary-container": "#89b4fa",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#174f1e",
        "inverse-surface": "#2d3134",
        "surface-tint": "#305f9f",
        "secondary-fixed": "#ffdbcb",
        "on-primary-fixed": "#001b3c",
        "outline": "#737781",
        "surface-dim": "#d8dade",
        "surface-container": "#eceef2",
        "surface-variant": "#e0e2e6",
        "tertiary-fixed": "#b4f2af",
        "error": "#ba1a1a",
        "on-background": "#191c1f",
        "primary": "#305f9f"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "base": "8px",
        "sm": "12px",
        "gutter": "16px",
        "margin-mobile": "20px",
        "md": "24px",
        "lg": "40px",
        "margin-desktop": "64px",
        "sidebar": "260px",
        "sidebar-width": "280px",
        "container-padding": "32px",
        "safe": "env(safe-area-inset-bottom)"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        "label-mono": ["monospace"]
      },
      fontSize: {
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "26px", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-mono": ["11px", { "lineHeight": "14px", "letterSpacing": "0.1em", "fontWeight": "500" }]
      }
    }
  }
}
